NhaSachMVC/Controllers/NguoiDungController.cs
using NhaSachMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NhaSachMVC.Controllers
{
    public class NguoiDungController : Controller
    {
        QLBANSACHEntities database = new QLBANSACHEntities();
        // GET: NguoiDung
        public ActionResult Index()
        {
            return View();
        }
        //lấy thông tin về 
        [HttpGet]
        public ActionResult DangKy() { 
        return View();
        }
        //kiểm nha rồi Post thông tin 
        [HttpPost]
        public ActionResult DangKy(KHACHHANG kh)
        {
            if (string.IsNullOrEmpty(kh.HoTenKH))
                ModelState.AddModelError(string.Empty, "Họ tên không được để trống");
            if (string.IsNullOrEmpty(kh.TenDN))
                ModelState.AddModelError(string.Empty, "Tên đăng nhập không được để trống");
            if (string.IsNullOrEmpty(kh.Matkhau))
                ModelState.AddModelError(string.Empty, "Mật khẩu không được để trống");
            if (string.IsNullOrEmpty(kh.Email))
                ModelState.AddModelError(string.Empty, "Email không được để trống");
            if (string.IsNullOrEmpty(kh.DienthoaiKH))
                ModelState.AddModelError(string.Empty, "Điện thoại không được để trống");

            // Kiểm tra số lượng chữ số của số điện thoại (Ví dụ: 10 chữ số)
            if (kh.DienthoaiKH.Length != 10)
                ModelState.AddModelError(string.Empty, "Số điện thoại phải có đúng 10 chữ số");
            var khachhang = database.KHACHHANGs.FirstOrDefault(k => k.TenDN == kh.TenDN);
            if (khachhang == null)
                ModelState.AddModelError(string.Empty, "Đã có người đăng ký tên này");
            if (ModelState.IsValid) {
                database.KHACHHANGs.Add(kh);
                database.SaveChanges();
            }
            else {
                return View();    
            }
            return RedirectToAction("DangNhap");
        }


        //Đăng nhập 
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(KHACHHANG kh)
        {
            if (ModelState.IsValid) //kiểm tra dữ liệu đầu vào có hợp lệ hay không
            {
                if (string.IsNullOrEmpty(kh.TenDN))
                    ModelState.AddModelError(string.Empty, "Tên đăng nhập không được để trống");
                if (string.IsNullOrEmpty(kh.Matkhau))
                    ModelState.AddModelError(string.Empty, "Mật khẩu không được để trống");
                if(ModelState.IsValid)
                {
                    var khach = database.KHACHHANGs.FirstOrDefault(k => k.TenDN == kh.TenDN && k.Matkhau == kh.Matkhau);
                    if (khach != null)
                    {
                        ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                        Session["TaiKhoan"] = khach;
                    }
                    else
                        ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";            
                     }
            }
            return View();
        }
    }
}

NhaSachMVC/Views/NguoiDung/DangKy.cshtml
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center">ĐĂNG KÝ THÀNH VIÊN</h2>
<br />
<div class="row">
    <div class="offset-md-1 col-md-10">
        @using (Html.BeginForm("DangKy", "NguoiDung"))
        {
            // Hiển thị thông báo nếu có lỗi
            @Html.ValidationSummary(true)

            <div class="form-group">
                <label for="name">Họ và Tên:</label>
                @Html.TextBox("HoTenKH", null, new { @class = "form-control", @id = "name", required = "required" })
                /*
                HoTenKH: nhận biến để gọi controller
                null: giá trị khi muốn hiển thị
                new: tạo một hiệu ứng html/css
                required = "required": không cho bỏ trống
                */
            </div>

            <div class="form-group">
                <label for="dangnhap">Tên đăng nhập:</label>
                @Html.TextBox("TenDN", null, new
                {
                    @class = "form-control",
                    @id = "dangnhap",
                    required = "required"
                })
            </div>

            <div class="form-group">
                <label for="matkhau">Mật khẩu:</label>
                @Html.Password("Matkhau", null, new
                {
                    @class = "form-control",
                    @id = "matkhau",
                    required = "required"
                })
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                @Html.TextBox("Email", null, new { 
                @class = "form-control", 
                @id = "dienthoai",
                 required = "required" })
            </div>
            <div class="form-group">
                <label for="diachi">Địa chỉ:</label>
                @Html.TextBox("DiachiKH", null, new
                {
                    @class = "form-control",
                    @id =
                "diachi"
                })
            </div>
            <div class="form-group">
                <label for="dienthoai">Điện thoại:</label>
                @Html.TextBox("DienthoaiKH", null, new
                {
                    @class = "form-control",
                    @id =
                "dienthoai",
                    required = "required"
                })
            </div>
            <div class="form-group">
                <label for="ngaysinh">Ngày sinh:</label>
                @Html.TextBox("Ngaysinh", null, new
                {
                    @class = "form-control",
                    @id =
                "ngaysinh",
                    type = "date",
                    placeholder = "mm/dd/yyyy"
                })
            </div>
            <button type="submit" class="btn btn-primary">ĐĂNG KÝ</button>
        }
    </div>
</div>

NhaSachMVC/Views/NguoiDung/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center">ĐĂNG NHẬP</h2>
<br />
<div class="row">

    <div class="offset-md-1 col-md-10">
        <h2 style="color: red;">@ViewBag.ThongBao</h2>
        @using (Html.BeginForm("DangNhap", "NguoiDung"))
        {
            @Html.ValidationSummary(true)
            <div class="form-group">
                <label for="dangnhap">Tên đăng nhập:</label>
                @Html.TextBox("TenDN", null, new
                {
                    @class = "form-control",
                    @id =
                "dangnhap",
                    required = "required"
                })
            </div>
            <div class="form-group">
                <label for="matkhau">Mật khẩu:</label>
                @Html.Password("Matkhau", null, new
                {
                    @class = "form-control",
                    @id =
                "matkhau",
                    required = "required"
                })
            </div>
            <button type="submit" class="btn btn-primary">ĐĂNG NHẬP</button>
        }
    </div>
</div>