NhaSachMVC/Models/BookStore.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

NhaSachMVC/Controllers/BookStoreController.cs
using NhaSachMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Web.UI;
namespace NhaSachMVC.Controllers
{
    public class BookStoreController : Controller
    {
        QLBANSACHEntities database = new QLBANSACHEntities();  
        // GET: BookStore

        public ActionResult Index(int? page)
        {
            //tạo biến số sách mỗi trang 
            int paseSize = 5;
            //tạo biến số trang 
            int PageNum = (page ?? 1);
            var dsSachMoi = LaySachMoi(5);
            return View(dsSachMoi);
        }

        private List<SACH> LaySachMoi(int soLuong)
        {
            //sắp xếp theo ngày cập nhật giảm dần
            //chuyển qua dạng danh sách kết quả đạt được 
            return database.SACHes.OrderByDescending(sach => sach.Ngaycapnhat).Take(soLuong).ToList();
        }
        //lấy danh sách trả về dưới dạng Partial View
        public ActionResult LayChuDe()
        {
            var dsChuDe = database.CHUDEs.ToList();
            return PartialView(dsChuDe);
        }
        //lấy danh sách trả về nhà xuất bản 
        public ActionResult LayNhaXuatBan()
        {
            var dsNhaXuatBan = database.NHAXUATBANs.ToList();
            return PartialView( dsNhaXuatBan);
        }
        //lấy sản phẩm theo chủ đề 
        public ActionResult SPTheoChuDe(int id)
        {
            var dsTheoChuDe = database.SACHes.Where(sach=> sach.MaCD == id).ToList();
            //trả về view sau khi sử dụng 
            return View("Index",dsTheoChuDe);

        }
        //lấy sản phẩm theo nhà xuất bản 
        public ActionResult SPtheoNXB(int id)
        {
            var dsTheoNXB = database.SACHes.Where(sach => sach.MaNXB == id);
            return View("Index", dsTheoNXB);
        }

        //lay chi tiết sản phẩm 
        public ActionResult Details(int id)
        {
            var sach = database.SACHes.FirstOrDefault(s => s.Masach == id);
            return View(sach);
        }
    }
}

NhaSachMVC/Views/BookStore/Details.cshtml
@using NhaSachMVC.Models
@model SACH

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>THÔNG TIN CHI TIẾT SÁCH</h2>
<br />
<div class="row">
    <div class="offset-md-1 col-md-4">
        <img style="width:100%" src="~/Images/@Model.Hinhminhhoa" />
    </div>
    <div class="col-md-6 details">
        <h3>@Model.Tensach</h3>
        <p style="text-align : justify">
            <span style="font-weight: bold">Mô tả</span>
        </p>
        <p class="price">
            Giá bán <span style="color:red; font-size: 32px">@Model.Dongia</span>
        </p>

        //đặt mua
        <a class="btn btn-primary" href="@Url.Action("ThemSanPhamVaoGio","GioHang", new {MaSp = Model.Masach})">Đặt mua</a>
    </div>
</div>

NhaSachMVC/Views/BookStore/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>ĐÂY LÀ TRANG CHỦ</h2>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="card col-sm-4 col-md-4 col-lg-4 d-flex align-items-stretch book-section">
            <a href="@Url.Action("Details","BookStore", new {id = sach.Masach})">
                <img class="card-img-top book-picture" src="~/Images/@sach.Hinhminhhoa" alt="Card-image"/>
            
            </a>
            <div class="card-body">
                <h4 class="card-title">@sach.Tensach</h4>
                <p class="card-text"> @sach.Dongia</p>
            </div>
        </div>
    }
</div>

NhaSachMVC/Views/BookStore/LayChuDe.cshtml
@using NhaSachMVC.Models
@model IEnumerable<CHUDE>

<div class="title">
    CHỦ ĐỀ SÁCH
</div>
<ul class="list-group">
    @foreach(var chude in Model)
            {
                <a href="@Url.Action("SPTheoChuDe","BookStore", new {id = chude.MaCD})" class="list-group-item list-group-item-action">
                    @chude.TenChuDe
                </a>
            }
</ul>

NhaSachMVC/Views/BookStore/LayNhaXuatBan.cshtml
@using NhaSachMVC.Models
@model IEnumerable<NHAXUATBAN>
<div class="title">NHÀ XUẤT BẢN</div>
<ul class="list-group">
    @foreach (var nxb in Model)
    {
        <a href="@Url.Action("SPTheoNXB", "BookStore", new { id=nxb.MaNXB })"
           class="list-group-item list-group-item-action">
            @nxb.TenNXB
        </a>
    }
</ul>